<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="MSTest.TestAdapter" PrivateAssets="all" />
    <ProjectReference Include="../../src/FileLens.Application/FileLens.Application.csproj" />
    <ProjectReference Include="../../src/FileLens.Infrastructure/FileLens.Infrastructure.csproj" />
  </ItemGroup>
</Project>
